apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: namespace-workflow-1719456782109
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80